### ISSUE TITLE
file not found for module `parse`

### ISSUE THREAD

**Issue by hce** [rodrigorc/pomelo#1]
Trying to compile master with rust nightly, getting this error:

       Compiling sqlite-parser v0.0.1 (/home/hc/caiberp/caibersuite/lemon-rs/parser)
    error[E0583]: file not found for module `parse`
     --> parser/src/lib.rs:7:9
      |
    7 | pub mod parse;
      |         ^^^^^
      |
      = help: name the file either parse.rs or parse/mod.rs inside the directory "parser/src"
    
What am I doing wrong/missing?

**Comment by rodrigorc** [comment]
@hce: Sorry I didn't see your issue before (my repo was unwatched).

I don't have any module named `parse`. I think that you may be using this repo as a clone, and adding it as a module instead of a crate?
