### ISSUE TITLE
[doc] better example of generic parser?

### ISSUE THREAD

**Issue by matbd** [rodrigorc/pomelo#3]
Hello, Would it make sense to add a longer example for generic parsers? (see below) IMHO the [current doc](https://docs.rs/pomelo/0.1.4/pomelo/index.html#generic-parsers) does not do justice to the awesomeness of Pomelo in this regard.
 
```rust
#![allow(unused_braces)]

#[macro_use]
extern crate pomelo;

pub trait Adder {
    type Value;
    fn from_int(&mut self, value: i32) -> Self::Value;
    fn add(&mut self, v1: Self::Value, v2: Self::Value) -> Self::Value;
}

pomelo! {
    %parser pub struct Parser<T: crate::Adder> {};
    %extra_argument T;

    %type input T::Value;
    %type numbers T::Value;
    %type Number i32;
    input ::= numbers?(A) { A.unwrap_or(extra.from_int(0)) };
    numbers ::= Number(N) { extra.from_int(N) }
    numbers ::= numbers(V) Comma Number(N) { let w = extra.from_int(N); extra.add(V, w) }
}

pub struct OpsCounter(usize);

impl Adder for OpsCounter {
    type Value = i32;

    fn from_int(&mut self, value: i32) -> Self::Value {
	value
    }

    fn add(&mut self, v1: Self::Value, v2: Self::Value) -> Self::Value {
	self.0 += 1;
	v1 + v2
    }
}

#[test]
fn test_parser() -> Result<(), ()> {
    use parser::{Parser, Token};
    let tokens = vec![
	Token::Number(1),
	Token::Comma,
	Token::Number(2),
	Token::Comma,
	Token::Number(3),
    ];
    let mut p = Parser::new(OpsCounter(0));
    for tok in tokens.into_iter() {
	p.parse(tok)?;
    }
    let (value, counter) = p.end_of_input()?;
    assert_eq!(value, 6);
    assert_eq!(counter.0, 2);
    Ok(())
}
```

**Comment by rodrigorc** [comment]
Sure! My main motivation to add generics to parsers was to be able to add lifetimes, so that is what the example goes with.

I didn't find a realistic use case where non-lifetime generics are actually useful, maybe because I was thinking of building an AST instead of doing computations in the parser, as your example above. Maybe you could add another `impl` to your example (such as a `Collector` that adds the values into a `Vec<i32>`, and open a pull-request?

**Comment by matbd** [comment]
Cool. Will do. My main use case is a modular parsing library where users can choose their term representation and have an arbitrary state modified during parsing. (Stateful parsing is obviously very useful, e.g. to share parsed values, or interpret commands directly.)

**Comment by matbd** [comment]
Incidentally, IMHO the current example with lifetimes would be more convincing with a shared reference. (For a mutable context, `Parser::new()` and `Parser::end_of_input()` could be used to move the context in and out without generics.)

**Comment by matbd** [comment]
Here is it: https://github.com/rodrigorc/pomelo/pull/4

**Comment by rodrigorc** [comment]
> Incidentally, IMHO the current example with lifetimes would be more convincing with a shared reference. (For an exclusive context, `Parser::new()` and `Parser::end_of_input()` can be used to move the data in and out without generics.)

I am more in the camp of snippets as short as possible, while still trying to make a point.

But yours are nice, too. And since they are the last in the doc page, they double as a kind of more complete example.

Merged, thank you!

**Comment by matbd** [comment]
@rodrigorc Thanks again for taking the PR. Do you know when the next (minor) release could be? (I'd like to share a link to the new docs)

**Comment by rodrigorc** [comment]
> @rodrigorc Thanks again for taking the PR. Do you know when the next (minor) release could be? (I'd like to share a link to the new docs)

I was thinking of rewriting the syntax of the "enum Token" but keeping compatibility with the old syntax is tricky... so updated to 0.1.5 just now.

**Comment by matbd** [comment]
Awesome, thanks!
